sudo: required
services:
  - docker

before_install:
  - docker build -t jxman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jxman/react-test npm test

after_success:
  - docker build -t jxman/multi-client ./client
  - docker build -t jxman/multi-ngix ./nginx
  - docker build -t jxman/multi-server ./server
  - docker build -t jxman/multi-worker ./worker
# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker test again
  - docker push jxman/multi-client
  - docker push jxman/multi-nginx
  - docker push jxman/multi-server
  - docker push jxman/multi-worker

deploy:
  provider: eleasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-600424110307
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
